package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElBook generated by hbm2java
 */
public class ElBook implements java.io.Serializable {

	private Integer id;
	private int active;
	private Date createDate;
	private Date updateDate;
	private String author;
	private String url;
	private String name;
	private String intro;

	public ElBook() {
	}

	public ElBook(int active, Date createDate, Date updateDate, String author,
			String url) {
		this.active = active;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.author = author;
		this.url = url;
	}

	public ElBook(int active, Date createDate, Date updateDate, String author,
			String url, String name, String intro) {
		this.active = active;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.author = author;
		this.url = url;
		this.name = name;
		this.intro = intro;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

}
