package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElCaptcha generated by hbm2java
 */
public class ElCaptcha implements java.io.Serializable {

	private Long captchaId;
	private int captchaTime;
	private String ipAddress;
	private String word;

	public ElCaptcha() {
	}

	public ElCaptcha(int captchaTime, String ipAddress, String word) {
		this.captchaTime = captchaTime;
		this.ipAddress = ipAddress;
		this.word = word;
	}

	public Long getCaptchaId() {
		return this.captchaId;
	}

	public void setCaptchaId(Long captchaId) {
		this.captchaId = captchaId;
	}

	public int getCaptchaTime() {
		return this.captchaTime;
	}

	public void setCaptchaTime(int captchaTime) {
		this.captchaTime = captchaTime;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

}
