package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElContact generated by hbm2java
 */
public class ElContact implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String name;
	private String email;
	private String mobile;
	private String message;

	public ElContact() {
	}

	public ElContact(int userId, String name) {
		this.userId = userId;
		this.name = name;
	}

	public ElContact(int userId, String name, String email, String mobile,
			String message) {
		this.userId = userId;
		this.name = name;
		this.email = email;
		this.mobile = mobile;
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
