package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElFile generated by hbm2java
 */
public class ElFile implements java.io.Serializable {

	private Integer id;
	private int active;
	private String path;
	private String shortPath;

	public ElFile() {
	}

	public ElFile(int active, String path) {
		this.active = active;
		this.path = path;
	}

	public ElFile(int active, String path, String shortPath) {
		this.active = active;
		this.path = path;
		this.shortPath = shortPath;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getShortPath() {
		return this.shortPath;
	}

	public void setShortPath(String shortPath) {
		this.shortPath = shortPath;
	}

}
