package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElMailFeedback generated by hbm2java
 */
public class ElMailFeedback implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String feedbackEmail;
	private String feedbackValue;
	private Date cliendDate;
	private Date serverDate;

	public ElMailFeedback() {
	}

	public ElMailFeedback(int userId, String feedbackEmail,
			String feedbackValue, Date cliendDate, Date serverDate) {
		this.userId = userId;
		this.feedbackEmail = feedbackEmail;
		this.feedbackValue = feedbackValue;
		this.cliendDate = cliendDate;
		this.serverDate = serverDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getFeedbackEmail() {
		return this.feedbackEmail;
	}

	public void setFeedbackEmail(String feedbackEmail) {
		this.feedbackEmail = feedbackEmail;
	}

	public String getFeedbackValue() {
		return this.feedbackValue;
	}

	public void setFeedbackValue(String feedbackValue) {
		this.feedbackValue = feedbackValue;
	}

	public Date getCliendDate() {
		return this.cliendDate;
	}

	public void setCliendDate(Date cliendDate) {
		this.cliendDate = cliendDate;
	}

	public Date getServerDate() {
		return this.serverDate;
	}

	public void setServerDate(Date serverDate) {
		this.serverDate = serverDate;
	}

}
