package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElMailSend generated by hbm2java
 */
public class ElMailSend implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String email;
	private String linkLive;
	private String linkDead;
	private Date senddate;

	public ElMailSend() {
	}

	public ElMailSend(int userId, String email, String linkLive,
			String linkDead, Date senddate) {
		this.userId = userId;
		this.email = email;
		this.linkLive = linkLive;
		this.linkDead = linkDead;
		this.senddate = senddate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLinkLive() {
		return this.linkLive;
	}

	public void setLinkLive(String linkLive) {
		this.linkLive = linkLive;
	}

	public String getLinkDead() {
		return this.linkDead;
	}

	public void setLinkDead(String linkDead) {
		this.linkDead = linkDead;
	}

	public Date getSenddate() {
		return this.senddate;
	}

	public void setSenddate(Date senddate) {
		this.senddate = senddate;
	}

}
