package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElNotice generated by hbm2java
 */
public class ElNotice implements java.io.Serializable {

	private ElNoticeId id;

	public ElNotice() {
	}

	public ElNotice(ElNoticeId id) {
		this.id = id;
	}

	public ElNoticeId getId() {
		return this.id;
	}

	public void setId(ElNoticeId id) {
		this.id = id;
	}

}
