package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElNoticeId generated by hbm2java
 */
public class ElNoticeId implements java.io.Serializable {

	private int id;
	private int userId;
	private Date readTime;
	private String title;
	private String content;
	private int status;
	private Date createDate;

	public ElNoticeId() {
	}

	public ElNoticeId(int id, int userId, Date readTime, String title,
			String content, int status, Date createDate) {
		this.id = id;
		this.userId = userId;
		this.readTime = readTime;
		this.title = title;
		this.content = content;
		this.status = status;
		this.createDate = createDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getReadTime() {
		return this.readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElNoticeId))
			return false;
		ElNoticeId castOther = (ElNoticeId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUserId() == castOther.getUserId())
				&& ((this.getReadTime() == castOther.getReadTime()) || (this
						.getReadTime() != null
						&& castOther.getReadTime() != null && this
						.getReadTime().equals(castOther.getReadTime())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getContent() == castOther.getContent()) || (this
						.getContent() != null && castOther.getContent() != null && this
						.getContent().equals(castOther.getContent())))
				&& (this.getStatus() == castOther.getStatus())
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getReadTime() == null ? 0 : this.getReadTime().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + this.getStatus();
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		return result;
	}

}
