package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElOrderId generated by hbm2java
 */
public class ElOrderId implements java.io.Serializable {

	private int id;
	private int userId;
	private String sku;
	private Date orderTime;
	private Date payTime;
	private int status;

	public ElOrderId() {
	}

	public ElOrderId(int id, int userId, String sku, Date orderTime,
			Date payTime, int status) {
		this.id = id;
		this.userId = userId;
		this.sku = sku;
		this.orderTime = orderTime;
		this.payTime = payTime;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElOrderId))
			return false;
		ElOrderId castOther = (ElOrderId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUserId() == castOther.getUserId())
				&& ((this.getSku() == castOther.getSku()) || (this.getSku() != null
						&& castOther.getSku() != null && this.getSku().equals(
						castOther.getSku())))
				&& ((this.getOrderTime() == castOther.getOrderTime()) || (this
						.getOrderTime() != null
						&& castOther.getOrderTime() != null && this
						.getOrderTime().equals(castOther.getOrderTime())))
				&& ((this.getPayTime() == castOther.getPayTime()) || (this
						.getPayTime() != null && castOther.getPayTime() != null && this
						.getPayTime().equals(castOther.getPayTime())))
				&& (this.getStatus() == castOther.getStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getSku() == null ? 0 : this.getSku().hashCode());
		result = 37 * result
				+ (getOrderTime() == null ? 0 : this.getOrderTime().hashCode());
		result = 37 * result
				+ (getPayTime() == null ? 0 : this.getPayTime().hashCode());
		result = 37 * result + this.getStatus();
		return result;
	}

}
