package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElOrder generated by hbm2java
 */
public class ElOrder implements java.io.Serializable {

	private ElOrderId id;

	public ElOrder() {
	}

	public ElOrder(ElOrderId id) {
		this.id = id;
	}

	public ElOrderId getId() {
		return this.id;
	}

	public void setId(ElOrderId id) {
		this.id = id;
	}

}
