package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElPostTag generated by hbm2java
 */
public class ElPostTag implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int postId;
	private int tagId;

	public ElPostTag() {
	}

	public ElPostTag(int userId, int postId, int tagId) {
		this.userId = userId;
		this.postId = postId;
		this.tagId = tagId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

}
