package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElStar generated by hbm2java
 */
public class ElStar implements java.io.Serializable {

	private Integer id;
	private String constellation;
	private String name;
	private String nick;
	private float dec;
	private float ra;
	private float v;
	private int userId;
	private int active;

	public ElStar() {
	}

	public ElStar(String constellation, String name, String nick, float dec,
			float ra, float v, int userId, int active) {
		this.constellation = constellation;
		this.name = name;
		this.nick = nick;
		this.dec = dec;
		this.ra = ra;
		this.v = v;
		this.userId = userId;
		this.active = active;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getConstellation() {
		return this.constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public float getDec() {
		return this.dec;
	}

	public void setDec(float dec) {
		this.dec = dec;
	}

	public float getRa() {
		return this.ra;
	}

	public void setRa(float ra) {
		this.ra = ra;
	}

	public float getV() {
		return this.v;
	}

	public void setV(float v) {
		this.v = v;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

}
