package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElTags generated by hbm2java
 */
public class ElTags implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int count;
	private String value;
	private int order;

	public ElTags() {
	}

	public ElTags(int userId, int count, String value, int order) {
		this.userId = userId;
		this.count = count;
		this.value = value;
		this.order = order;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

}
