package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUrl generated by hbm2java
 */
public class ElUrl implements java.io.Serializable {

	private ElUrlId id;

	public ElUrl() {
	}

	public ElUrl(ElUrlId id) {
		this.id = id;
	}

	public ElUrlId getId() {
		return this.id;
	}

	public void setId(ElUrlId id) {
		this.id = id;
	}

}
