package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUserFavPost generated by hbm2java
 */
public class ElUserFavPost implements java.io.Serializable {

	private ElUserFavPostId id;

	public ElUserFavPost() {
	}

	public ElUserFavPost(ElUserFavPostId id) {
		this.id = id;
	}

	public ElUserFavPostId getId() {
		return this.id;
	}

	public void setId(ElUserFavPostId id) {
		this.id = id;
	}

}
