package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUserFavorite generated by hbm2java
 */
public class ElUserFavorite implements java.io.Serializable {

	private ElUserFavoriteId id;

	public ElUserFavorite() {
	}

	public ElUserFavorite(ElUserFavoriteId id) {
		this.id = id;
	}

	public ElUserFavoriteId getId() {
		return this.id;
	}

	public void setId(ElUserFavoriteId id) {
		this.id = id;
	}

}
