package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElUserLog generated by hbm2java
 */
public class ElUserLog implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private Date datetime;
	private int ip;
	private int status;

	public ElUserLog() {
	}

	public ElUserLog(String username, String email, Date datetime, int ip,
			int status) {
		this.username = username;
		this.email = email;
		this.datetime = datetime;
		this.ip = ip;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public int getIp() {
		return this.ip;
	}

	public void setIp(int ip) {
		this.ip = ip;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
