package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUserStarStatus generated by hbm2java
 */
public class ElUserStarStatus implements java.io.Serializable {

	private ElUserStarStatusId id;

	public ElUserStarStatus() {
	}

	public ElUserStarStatus(ElUserStarStatusId id) {
		this.id = id;
	}

	public ElUserStarStatusId getId() {
		return this.id;
	}

	public void setId(ElUserStarStatusId id) {
		this.id = id;
	}

}
