package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ElUser generated by hbm2java
 */
public class ElUser implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String password2;
	private String avatar;
	private String username;
	private String displayName;
	private String realName;
	private boolean gender;
	private Date birthdate;
	private int level;
	private Date vipDeadline;
	private int starId;
	private int status;
	private boolean active;
	private String place;
	private String school;
	private String intro;
	private String tags;
	private String career;
	private int dataUsed;
	private Date createDate;

	public ElUser() {
	}

	public ElUser(String password2, String username, boolean gender,
			Date birthdate, int level, Date vipDeadline, int starId,
			int status, boolean active, String school, String intro,
			String tags, String career, int dataUsed, Date createDate) {
		this.password2 = password2;
		this.username = username;
		this.gender = gender;
		this.birthdate = birthdate;
		this.level = level;
		this.vipDeadline = vipDeadline;
		this.starId = starId;
		this.status = status;
		this.active = active;
		this.school = school;
		this.intro = intro;
		this.tags = tags;
		this.career = career;
		this.dataUsed = dataUsed;
		this.createDate = createDate;
	}

	public ElUser(String email, String password, String password2,
			String avatar, String username, String displayName,
			String realName, boolean gender, Date birthdate, int level,
			Date vipDeadline, int starId, int status, boolean active,
			String place, String school, String intro, String tags,
			String career, int dataUsed, Date createDate) {
		this.email = email;
		this.password = password;
		this.password2 = password2;
		this.avatar = avatar;
		this.username = username;
		this.displayName = displayName;
		this.realName = realName;
		this.gender = gender;
		this.birthdate = birthdate;
		this.level = level;
		this.vipDeadline = vipDeadline;
		this.starId = starId;
		this.status = status;
		this.active = active;
		this.place = place;
		this.school = school;
		this.intro = intro;
		this.tags = tags;
		this.career = career;
		this.dataUsed = dataUsed;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword2() {
		return this.password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public boolean isGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public Date getVipDeadline() {
		return this.vipDeadline;
	}

	public void setVipDeadline(Date vipDeadline) {
		this.vipDeadline = vipDeadline;
	}

	public int getStarId() {
		return this.starId;
	}

	public void setStarId(int starId) {
		this.starId = starId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public String getCareer() {
		return this.career;
	}

	public void setCareer(String career) {
		this.career = career;
	}

	public int getDataUsed() {
		return this.dataUsed;
	}

	public void setDataUsed(int dataUsed) {
		this.dataUsed = dataUsed;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
