package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUserFavUser generated by hbm2java
 */
public class ElUserFavUser implements java.io.Serializable {

	private ElUserFavUserId id;

	public ElUserFavUser() {
	}

	public ElUserFavUser(ElUserFavUserId id) {
		this.id = id;
	}

	public ElUserFavUserId getId() {
		return this.id;
	}

	public void setId(ElUserFavUserId id) {
		this.id = id;
	}

}
