package com.everlive.user.bo;

// Generated 2014-1-5 15:12:46 by Hibernate Tools 3.2.2.GA

/**
 * ElUserPlace generated by hbm2java
 */
public class ElUserPlace implements java.io.Serializable {

	private ElUserPlaceId id;

	public ElUserPlace() {
	}

	public ElUserPlace(ElUserPlaceId id) {
		this.id = id;
	}

	public ElUserPlaceId getId() {
		return this.id;
	}

	public void setId(ElUserPlaceId id) {
		this.id = id;
	}

}
